### 넘파이(Numpy) : 배열(ndarray, n dimension array)
#### 리스트(list): Linked List 구조(불연속), 동작 속도가 느리다, comma로 요소 구별, 서로 다른 자료형 사용가능
#### 배열(ndarray) : 연속된 메모리 구조, 동작 속도가 빠르다, comma를 사용하지 않고 공백으로 요소를 구별, 오직 한 가지 타입만 갖을 수 있다

In [6]:
import numpy as np

# list
list1 = [0,1,2,3,4,5,'Hello',10.5]
print(list1,type(list1))

# ndarray
a = np.array([0,1,2,3,4,5])   # 1차원 배열
print(a,type(a))   

[0, 1, 2, 3, 4, 5, 'Hello', 10.5] <class 'list'>
[0 1 2 3 4 5] <class 'numpy.ndarray'>


In [18]:
# 2차원 배열의 Shape : 행(row,가로,수직,axis=0)과 열(column,세로,수평,axis=1) => 필수암기 
list1 = [[0,1,2],
         [3,4,5]]
print(list1)

m = np.array(list1)
print(m)
print(m.shape)  # (2, 3)

[[0, 1, 2], [3, 4, 5]]
[[0 1 2]
 [3 4 5]]
(2, 3)


In [42]:
### 2차원 배열의 인덱싱과 슬라이싱 :  data[행,열]
print(m)

# 인덱싱
print(m[0,0])  # 0
print(m[0,1])  # 1
print(m[1,1])  # 4
print(m[1,2])  # 5
print(m[-1,-1])  # 5

# 슬라이싱
print(m[0:2,0:2])  
print(m[:,:2])   
print(m[0:2,1:]) 

[[0 1 2]
 [3 4 5]]
0
1
4
5
5
[[0 1]
 [3 4]]
[[0 1]
 [3 4]]
[[1 2]
 [4 5]]


### Pandas
#### (1) DataFrame 객체 : 2차원 배열, 서로 다른 자료형을 사용할 수 있다,  행(인스턴스), 열(컬럼,피쳐(feature))
#### (2) Series 객체  : 1차원 배열, 1차원 ndarray 와 호환

In [60]:
import pandas as pd

# 사전(dict)을 사용하여 생성
score_table = { '성명': ['홍길동','김철수','김영희','나','너'],
                '국어': [50,60,70,80,90],
                '영어': [10,np.nan,30,40,50],
                '수학': [70,80,90,30,20]}

# print(score_table,type(score_table))

df = pd.DataFrame(score_table)
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


성명  국어    영어  수학
0  홍길동  50  10.0  70
1  김철수  60   NaN  80
2  김영희  70  30.0  90
3    나  80  40.0  30
4    너  90  50.0  20

### pandas 로 csv 파일 읽고 쓰기
* df = pd.read_csv('파일명')
* df.to_csv('파일명')

In [66]:
df = pd.read_csv('WHO_first9cols.csv')
print(type(df))
df

# NaN : Not a Number , 결측치

<class 'pandas.core.frame.DataFrame'>


Country  CountryID  Continent  Adolescent fertility rate (%)  \
0           Afghanistan          1          1                          151.0   
1               Albania          2          2                           27.0   
2               Algeria          3          3                            6.0   
3               Andorra          4          2                            NaN   
4                Angola          5          3                          146.0   
..                  ...        ...        ...                            ...   
197             Vietnam        198          6                           25.0   
198  West Bank and Gaza        199          1                            NaN   
199               Yemen        200          1                           83.0   
200              Zambia        201          3                          161.0   
201            Zimbabwe        202          3                          101.0   

     Adult literacy rate (%)  \
0                       28.0   
1                       98.7   
2                       69.9   
3                        NaN   
4                       67.4   
..                       ...   
197                     90.3   
198                      NaN   
199                     54.1   
200                     68.0   
201                     89.5   

     Gross national income per capita (PPP international $)  \
0                                                  NaN        
1                                               6000.0        
2                                               5940.0        
3                                                  NaN        
4                                               3890.0        
..                                                 ...        
197                                             2310.0        
198                                                NaN        
199                                             2090.0        
200                                             1140.0        
201                                                NaN        

     Net primary school enrolment ratio female (%)  \
0                                              NaN   
1                                             93.0   
2                                             94.0   
3                                             83.0   
4                                             49.0   
..                                             ...   
197                                           91.0   
198                                            NaN   
199                                           65.0   
200                                           94.0   
201                                           88.0   

     Net primary school enrolment ratio male (%)  \
0                                            NaN   
1                                           94.0   
2                                           96.0   
3                                           83.0   
4                                           51.0   
..                                           ...   
197                                         96.0   
198                                          NaN   
199                                         85.0   
200                                         90.0   
201                                         87.0   

     Population (in thousands) total  
0                            26088.0  
1                             3172.0  
2                            33351.0  
3                               74.0  
4                            16557.0  
..                               ...  
197                          86206.0  
198                              NaN  
199                          21732.0  
200                          11696.0  
201                          13228.0  

[202 rows x 9 columns]

In [70]:
# csv 파일을 저장하기
df.to_csv('세계보건기구_9개컬럼.csv',index=False)
# index = False , 인덱스 값이 추가로 저장되지 않도록 설정